#!/usr/bin/perl
use strict;
use warnings 'FATAL' => 'all';
require './modules/pid.ph';

our ($ROOT, $MAP_URL);

my $pinfo = CGObject()->path_info();
if ($pinfo eq '' || $pinfo eq '/' || $pinfo eq '/index.html')
{
  Redirect("$MAP_URL/full20/");
}
elsif ($pinfo =~ m!^/level(\d\d)\.html$!)
{
  Redirect("$MAP_URL/full20/level0$1.html");
}
NotFound();
